[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --strict-markers
    --html=reports/reporte_pruebas.html
    --self-contained-html
    --capture=tee-sys
markers =
    hu: historia de usuario asociada al escenario
    feliz: escenario de camino feliz
    negativa: escenario de prueba negativa
    limites: escenario de prueba de limites
